# Generated by Django 3.0.8 on 2020-08-06 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idnum', models.CharField(max_length=17, unique=True)),
                ('name', models.CharField(default='None', max_length=64)),
                ('gender', models.CharField(max_length=8, null=True)),
                ('age', models.IntegerField(default=1)),
                ('doctor', models.CharField(default='None', max_length=64)),
                ('description', models.CharField(default='None', max_length=512, null=True)),
                ('ddescription', models.CharField(default='None', max_length=512)),
                ('devicetype', models.CharField(default='Medtronic', max_length=128)),
                ('surgerytime', models.DateTimeField(default=django.utils.timezone.now)),
                ('surgerypos', models.CharField(default='', max_length=128)),
                ('imgpath', models.CharField(default='', max_length=512)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
