# Generated by Django 3.0.8 on 2020-09-26 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('author', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryApproach',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('author', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idnum', models.CharField(max_length=17, unique=True)),
                ('name', models.CharField(default='Patient', max_length=64)),
                ('avatar', models.CharField(default='', max_length=2048)),
                ('gender', models.IntegerField(default=1, null=True)),
                ('birthday', models.DateField(default=django.utils.timezone.localdate)),
                ('surgerytime', models.DateTimeField(default=django.utils.timezone.now)),
                ('surgerycenter', models.CharField(default='', max_length=128)),
                ('phone', models.CharField(default='', max_length=11)),
                ('doctor', models.IntegerField()),
                ('remark', models.CharField(default='', max_length=4096)),
                ('valid', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('devicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.DeviceType')),
                ('surgerytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.SurgeryApproach')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(default='', max_length=255, unique=True)),
                ('filetype', models.IntegerField(default=1)),
                ('remark', models.CharField(default='', max_length=2048)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctors')),
            ],
        ),
    ]
