# Generated by Django 3.0.8 on 2020-08-08 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('filename', models.CharField(default='', max_length=255, unique=True)),
                ('filetype', models.IntegerField(default=1)),
                ('remark', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idnum', models.CharField(max_length=17, unique=True)),
                ('name', models.CharField(default='Patient', max_length=64)),
                ('avatar', models.CharField(default='', max_length=2048)),
                ('gender', models.IntegerField(default=1, null=True)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('surgerytime', models.DateTimeField(default=django.utils.timezone.now)),
                ('surgerycenter', models.CharField(default='', max_length=128)),
                ('surgerytype', models.IntegerField(default=1)),
                ('devicetype', models.IntegerField(default=1)),
                ('phone', models.CharField(default='', max_length=11)),
                ('doctor', models.IntegerField()),
                ('remark', models.CharField(default='', max_length=4096)),
                ('valid', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
