# Generated by Django 3.0.8 on 2020-08-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='surgerytype',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
