# Generated by Django 3.0.8 on 2020-08-07 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patients_surgerytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('filename', models.CharField(default='', max_length=2048)),
                ('filetype', models.IntegerField(default=1)),
                ('remark', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='surgerypos',
            new_name='surgerycenter',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='age',
            new_name='valid',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='ddescription',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='description',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='imgpath',
        ),
        migrations.AddField(
            model_name='patients',
            name='avatar',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='patients',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patients',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='patients',
            name='remark',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='patients',
            name='devicetype',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='patients',
            name='doctor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='name',
            field=models.CharField(default='Patient', max_length=64),
        ),
        migrations.AlterField(
            model_name='patients',
            name='surgerytype',
            field=models.IntegerField(default=1),
        ),
    ]
